"""Adding buy rate to Sell table

Revision ID: b906d88931e4
Revises: 5a5fbdd4e884
Create Date: 2024-08-20 19:27:32.855514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b906d88931e4'
down_revision: Union[str, None] = '5a5fbdd4e884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sells', sa.Column('buy_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sells', 'buy_rate')
    # ### end Alembic commands ###
